apiVersion: v1
kind: Service
metadata:
  name: ai-k8s-backend
  namespace: ai-k8s-ops
spec:
  selector:
    app: ai-k8s-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP