apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-k8s-backend-hpa
  namespace: ai-k8s-ops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-k8s-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60