apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-k8s-ops-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/ai-k8s-ops-platform.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-k8s-ops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true